# Generated by Django 2.1.8 on 2019-05-06 01:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_my', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description_en', models.TextField(blank=True, verbose_name='Description')),
                ('description_my', models.TextField(blank=True, verbose_name='Description')),
                ('body_en', wagtail.core.fields.StreamField([('CardLinks', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, help_text="\n    The CardLink will link to this page. The card displays the page's hero\n    image and description.\n    ", label='Choose a page', target_model=['home.WebPage']))]), template='home/list_block_card_link.html')), ('Postcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text="The description's title.", label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image that the description will accompany.', label='Image')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text that describes or accompanies the image.', label='Description'))])), ('Quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(help_text="The quote's body text.", label='Quote Text')), ('attribution', wagtail.core.blocks.CharBlock(help_text='Whom or what the text quotes.', label='Attribution', max_length=255, required=False))])), ('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed'])), ('Title', wagtail.core.blocks.StructBlock([('big_title', wagtail.core.blocks.CharBlock(help_text='This title displays larger in the block.', label='The Big Title', max_length=255)), ('small_title', wagtail.core.blocks.CharBlock(help_text='This title displays smaller in the block.', label='The Small Title', max_length=255))]))], blank=True, help_text='\n    You can create page content with "blocks". With the "RichText" block, you\n    can write with headers, bold and italic text, lists, images, anchors,\n    document links, and embed links.\n    ', verbose_name='body')),
                ('body_my', wagtail.core.fields.StreamField([('CardLinks', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, help_text="\n    The CardLink will link to this page. The card displays the page's hero\n    image and description.\n    ", label='Choose a page', target_model=['home.WebPage']))]), template='home/list_block_card_link.html')), ('Postcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text="The description's title.", label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image that the description will accompany.', label='Image')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text that describes or accompanies the image.', label='Description'))])), ('Quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(help_text="The quote's body text.", label='Quote Text')), ('attribution', wagtail.core.blocks.CharBlock(help_text='Whom or what the text quotes.', label='Attribution', max_length=255, required=False))])), ('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed'])), ('Title', wagtail.core.blocks.StructBlock([('big_title', wagtail.core.blocks.CharBlock(help_text='This title displays larger in the block.', label='The Big Title', max_length=255)), ('small_title', wagtail.core.blocks.CharBlock(help_text='This title displays smaller in the block.', label='The Small Title', max_length=255))]))], blank=True, help_text='\n    You can create page content with "blocks". With the "RichText" block, you\n    can write with headers, bold and italic text, lists, images, anchors,\n    document links, and embed links.\n    ', verbose_name='body')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
