# Generated by Django 2.1.8 on 2019-05-13 06:13

from django.db import migrations
import home.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_model_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('Title', wagtail.core.blocks.StructBlock([('big_title', wagtail.core.blocks.CharBlock(help_text='This title displays larger in the block.', label='The Big Title', max_length=255)), ('small_title', wagtail.core.blocks.CharBlock(help_text='This title displays smaller in the block.', label='The Small Title', max_length=255))], label='Title')), ('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed'], label='Rich-text')), ('CardLinks', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, help_text="\n    The CardLink will link to this page. The card displays the page's hero\n    image and description.\n    ", label='Choose a page', target_model=['home.WebPage']))], label='Card Links'), template='home/list_block_card_link.html')), ('Postcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text="The description's title.", label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image that the description will accompany.', label='Image')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text that describes or accompanies the image.', label='Description'))], label='Postcard')), ('Quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(help_text="The quote's body text.", label='Quote Text')), ('attribution', wagtail.core.blocks.CharBlock(help_text='Whom or what the text quotes.', label='Attribution', max_length=255, required=False))], label='Quote')), ('Line', home.blocks.LineBlock(label='Line'))], blank=True, help_text='\n    You can create page content with "blocks". With the "RichText" block, you\n    can write with headers, bold and italic text, lists, images, anchors,\n    document links, and embed links.\n    ', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='body_my',
            field=wagtail.core.fields.StreamField([('Title', wagtail.core.blocks.StructBlock([('big_title', wagtail.core.blocks.CharBlock(help_text='This title displays larger in the block.', label='The Big Title', max_length=255)), ('small_title', wagtail.core.blocks.CharBlock(help_text='This title displays smaller in the block.', label='The Small Title', max_length=255))], label='Title')), ('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed'], label='Rich-text')), ('CardLinks', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, help_text="\n    The CardLink will link to this page. The card displays the page's hero\n    image and description.\n    ", label='Choose a page', target_model=['home.WebPage']))], label='Card Links'), template='home/list_block_card_link.html')), ('Postcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text="The description's title.", label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image that the description will accompany.', label='Image')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text that describes or accompanies the image.', label='Description'))], label='Postcard')), ('Quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(help_text="The quote's body text.", label='Quote Text')), ('attribution', wagtail.core.blocks.CharBlock(help_text='Whom or what the text quotes.', label='Attribution', max_length=255, required=False))], label='Quote')), ('Line', home.blocks.LineBlock(label='Line'))], blank=True, help_text='\n    You can create page content with "blocks". With the "RichText" block, you\n    can write with headers, bold and italic text, lists, images, anchors,\n    document links, and embed links.\n    ', verbose_name='body'),
        ),
    ]
