# Generated by Django 2.1.8 on 2019-04-17 07:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_page_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='description_my',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed']))], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_my',
            field=wagtail.core.fields.StreamField([('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed']))], blank=True),
        ),
    ]
