# Generated by Django 2.1.8 on 2019-04-23 01:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_adds_quote_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed'])), ('Quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(help_text="The quote's body text.", label='Quote Text')), ('attribution', wagtail.core.blocks.CharBlock(help_text='Whom or what the text quotes.', label='Attribution', max_length=255, required=False))])), ('Postcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text="The description's title.", label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image that the description will accompany.', label='Image')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text that describes or accompanies the image.', label='Description'))]))], blank=True, help_text='\n    You can create page content with "blocks". With the "RichText" block, you\n    can write with headers, bold and italic text, lists, images, anchors,\n    document links, and embed links.\n    ', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_my',
            field=wagtail.core.fields.StreamField([('RichText', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'ol', 'ul', 'link', 'document-link', 'image', 'embed'])), ('Quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.BlockQuoteBlock(help_text="The quote's body text.", label='Quote Text')), ('attribution', wagtail.core.blocks.CharBlock(help_text='Whom or what the text quotes.', label='Attribution', max_length=255, required=False))])), ('Postcard', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text="The description's title.", label='Title', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='An image that the description will accompany.', label='Image')), ('description', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text that describes or accompanies the image.', label='Description'))]))], blank=True, help_text='\n    You can create page content with "blocks". With the "RichText" block, you\n    can write with headers, bold and italic text, lists, images, anchors,\n    document links, and embed links.\n    ', verbose_name='body'),
        ),
    ]
